version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: adminer
    restart: always
    ports:
      - 8081:8080